name: Deploy FastAPI API (prod)

on:
  push:
    branches: [ main ]
    paths:
      - 'doctagger_backend/**'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: doctagger-api-prod           # <-- your Web App name
          package: .                             # deploy repo root (includes requirements.txt)
