name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Build and Deploy
    steps:
      # 1) Checkout
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # 2) Node 20 + cache + build (in your SPA folder)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: doctagger_ui_frontend/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: doctagger_ui_frontend

      - name: Build SPA
        run: npm run build
        working-directory: doctagger_ui_frontend

      # 3) Get OIDC ID token (note: do NOT redeclare 'core')
      - name: Get OIDC ID token
        id: oidc
        uses: actions/github-script@v6
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      # 4) Deploy the already-built files (skip auto build)
      - name: Deploy to Azure Static Web Apps (OIDC)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: doctagger_ui_frontend   # source root
          output_location: dist                 # built folder (relative to app_location)
          skip_app_build: true
          github_id_token: ${{ steps.oidc.outputs.result }}
          production_branch: main
          deployment_environment: Production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR environment
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
