name: Backend CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👉 keep backend in lockstep with daemon's shared/
      - name: Copy canonical shared/ into backend
        run: |
          rm -rf doctagger_backend/shared
          cp -R doc_tagger_daemon/shared doctagger_backend/shared
          ls -la doctagger_backend/shared

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: doctagger_backend
        run: |
          python -m pip install --upgrade pip
          if [ -f ../requirements.txt ]; then pip install -r ../requirements.txt; fi
          pip install -r requirements.txt

      # Optional: run tests if you have them
      # - name: Run tests
      #   working-directory: doctagger_backend
      #   run: pytest -q

      # --- Deploy (choose one and remove the others) -------------------------
      # Option A: Azure Web App (Linux) via publish profile (easiest)
      #   - Create an App Service (Python 3.11)
      #   - In the App, get "Publish profile" and save it as a secret: AZURE_WEBAPP_PUBLISH_PROFILE
      #   - Set APP_NAME below to your web app name
      - name: Deploy to Azure Web App (via publish profile)
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE != '' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: <YOUR_WEBAPP_NAME>          # TODO: set this
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: doctagger_backend
      # ----------------------------------------------------------------------

      # Option B (placeholder): no deploy yet
      - name: No deploy configured
        if: ${{ !secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        run: echo "No deploy step configured. Backend built OK."
